### ISSUE TITLE
Catalogue can be sorted

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/Alexandria#60]
- [ ] Add API params for sorting books (#44) (@hawkw)
 - [ ] Add API params for sorting authors (#59) (@hawkw)
 - [ ] Add sorting support for books to the backend #58  (@hawkw)
 - [ ] Add sorting to frontend (@redbassett)
